import { createSlice } from "@reduxjs/toolkit";

const historicDataSlice = createSlice({
    name: 'historicData',
    initialState: {
        index: 1,
        noiseSensor: {
            "code": 1000,
            "message": "成功",
            "data": {
                "deviceAddr": 21068083,
                "groupId": "c166f67a8f504f97bafd10e0c9032e21",
                "deviceName": "室外噪声传感器",
                "offlineinterval": 10,
                "savedatainterval": 10,
                "alarmSwitch": 3,
                "alarmRecord": 1,
                "lng": 115.988705,
                "lat": 40.448054,
                "useMarkLocation": true,
                "sort": 0,
                "deviceType": "",
                "factors": [
                    {
                        "factorId": "21068083_1_1",
                        "deviceAddr": 21068083,
                        "nodeId": 1,
                        "registerId": 1,
                        "factorName": "噪声",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    }
                ],
                "deviceCode": "e9b507271fa9b12d8c35178f2c13074c",
                "protocol": "v2"
            }
        },
        airSensor: {
            "code": 1000,
            "message": "成功",
            "data": {
                "deviceAddr": 21072372,
                "groupId": "c166f67a8f504f97bafd10e0c9032e21",
                "deviceName": "室内空气质量监测仪",
                "offlineinterval": 10,
                "savedatainterval": 10,
                "alarmSwitch": 3,
                "alarmRecord": 1,
                "lng": 115.988705,
                "lat": 40.448054,
                "useMarkLocation": true,
                "sort": 0,
                "deviceType": "",
                "factors": [
                    {
                        "factorId": "21072372_1_1",
                        "deviceAddr": 21072372,
                        "nodeId": 1,
                        "registerId": 1,
                        "factorName": "PM10",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "μg/m³",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_1_2",
                        "deviceAddr": 21072372,
                        "nodeId": 1,
                        "registerId": 2,
                        "factorName": "PM2.5",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "μg/m³",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_2_1",
                        "deviceAddr": 21072372,
                        "nodeId": 2,
                        "registerId": 1,
                        "factorName": "温度",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_2_2",
                        "deviceAddr": 21072372,
                        "nodeId": 2,
                        "registerId": 2,
                        "factorName": "湿度",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%RH",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_5_2",
                        "deviceAddr": 21072372,
                        "nodeId": 5,
                        "registerId": 2,
                        "factorName": "TVOC",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppb",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_7_1",
                        "deviceAddr": 21072372,
                        "nodeId": 7,
                        "registerId": 1,
                        "factorName": "甲醛",
                        "factorIcon": "0.png",
                        "coefficient": 0.01,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppm",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_8_1",
                        "deviceAddr": 21072372,
                        "nodeId": 8,
                        "registerId": 1,
                        "factorName": "臭氧",
                        "factorIcon": "0.png",
                        "coefficient": 0.01,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppm",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_12_1",
                        "deviceAddr": 21072372,
                        "nodeId": 12,
                        "registerId": 1,
                        "factorName": "一氧化碳",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppm",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_13_1",
                        "deviceAddr": 21072372,
                        "nodeId": 13,
                        "registerId": 1,
                        "factorName": "二氧化氮",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppm",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_14_1",
                        "deviceAddr": 21072372,
                        "nodeId": 14,
                        "registerId": 1,
                        "factorName": "二氧化硫",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "ppm",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "21072372_19_1",
                        "deviceAddr": 21072372,
                        "nodeId": 19,
                        "registerId": 1,
                        "factorName": "TSP",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "μg/m³",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    }
                ],
                "deviceCode": "c249085a29f8f93ffd5375ed89867af8",
                "protocol": "v2"
            }
        },
        hostSensor: {
            "code": 1000,
            "message": "成功",
            "data": {
                "deviceAddr": 40274120,
                "groupId": "c166f67a8f504f97bafd10e0c9032e21",
                "deviceName": "智能监控主机",
                "offlineinterval": 10,
                "savedatainterval": 10,
                "alarmSwitch": 3,
                "alarmRecord": 1,
                "lng": 115.988705,
                "lat": 40.448054,
                "useMarkLocation": true,
                "sort": 0,
                "deviceType": "",
                "factors": [
                    {
                        "factorId": "40274120_1_2",
                        "deviceAddr": 40274120,
                        "nodeId": 1,
                        "registerId": 2,
                        "factorName": "厨房-噪声-ZS-1",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_2_2",
                        "deviceAddr": 40274120,
                        "nodeId": 2,
                        "registerId": 2,
                        "factorName": "卧室2-噪声-ZS-2",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_3_2",
                        "deviceAddr": 40274120,
                        "nodeId": 3,
                        "registerId": 2,
                        "factorName": "起居室-噪声-ZS-4",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_4_2",
                        "deviceAddr": 40274120,
                        "nodeId": 4,
                        "registerId": 2,
                        "factorName": "卧室-噪声-ZS-3",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_5_2",
                        "deviceAddr": 40274120,
                        "nodeId": 5,
                        "registerId": 2,
                        "factorName": "主卧-噪声-ZS-5",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_6_2",
                        "deviceAddr": 40274120,
                        "nodeId": 6,
                        "registerId": 2,
                        "factorName": "卧室3-噪声-ZS-6",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "dB",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_7_2",
                        "deviceAddr": 40274120,
                        "nodeId": 7,
                        "registerId": 2,
                        "factorName": "卧室2-风速-FS-1",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "m/s",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_8_2",
                        "deviceAddr": 40274120,
                        "nodeId": 8,
                        "registerId": 2,
                        "factorName": "起居室-风速-FS-2",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "m/s",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_9_2",
                        "deviceAddr": 40274120,
                        "nodeId": 9,
                        "registerId": 2,
                        "factorName": "主卧-风速-FS-3",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "m/s",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_10_1",
                        "deviceAddr": 40274120,
                        "nodeId": 10,
                        "registerId": 1,
                        "factorName": "厨房-温度-GZ-1",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_10_2",
                        "deviceAddr": 40274120,
                        "nodeId": 10,
                        "registerId": 2,
                        "factorName": "厨房-湿度-GZ-1",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_11_1",
                        "deviceAddr": 40274120,
                        "nodeId": 11,
                        "registerId": 1,
                        "factorName": "厨房-温度-GZ-2",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_11_2",
                        "deviceAddr": 40274120,
                        "nodeId": 11,
                        "registerId": 2,
                        "factorName": "厨房-湿度-GZ-2",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_12_1",
                        "deviceAddr": 40274120,
                        "nodeId": 12,
                        "registerId": 1,
                        "factorName": "厨房-温度-GZ-4",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_12_2",
                        "deviceAddr": 40274120,
                        "nodeId": 12,
                        "registerId": 2,
                        "factorName": "厨房-湿度-GZ-4",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_13_1",
                        "deviceAddr": 40274120,
                        "nodeId": 13,
                        "registerId": 1,
                        "factorName": "西厨-温度-GZ-3",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_13_2",
                        "deviceAddr": 40274120,
                        "nodeId": 13,
                        "registerId": 2,
                        "factorName": "西厨-湿度-GZ-3",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_14_1",
                        "deviceAddr": 40274120,
                        "nodeId": 14,
                        "registerId": 1,
                        "factorName": "卧室2-温度-GZ-6",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_14_2",
                        "deviceAddr": 40274120,
                        "nodeId": 14,
                        "registerId": 2,
                        "factorName": "卧室2-湿度-GZ-6",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_15_1",
                        "deviceAddr": 40274120,
                        "nodeId": 15,
                        "registerId": 1,
                        "factorName": "卧室2-温度-GZ-7",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_15_2",
                        "deviceAddr": 40274120,
                        "nodeId": 15,
                        "registerId": 2,
                        "factorName": "卧室2-湿度-GZ-7",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_16_1",
                        "deviceAddr": 40274120,
                        "nodeId": 16,
                        "registerId": 1,
                        "factorName": "餐厅-温度-GZ-5",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_16_2",
                        "deviceAddr": 40274120,
                        "nodeId": 16,
                        "registerId": 2,
                        "factorName": "餐厅-湿度-GZ-5",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_17_1",
                        "deviceAddr": 40274120,
                        "nodeId": 17,
                        "registerId": 1,
                        "factorName": "阳台-温度-GZ-8",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_17_2",
                        "deviceAddr": 40274120,
                        "nodeId": 17,
                        "registerId": 2,
                        "factorName": "阳台-湿度-GZ-8",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_18_1",
                        "deviceAddr": 40274120,
                        "nodeId": 18,
                        "registerId": 1,
                        "factorName": "阳台-温度-GZ-9",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_18_2",
                        "deviceAddr": 40274120,
                        "nodeId": 18,
                        "registerId": 2,
                        "factorName": "阳台-湿度-GZ-9",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_19_1",
                        "deviceAddr": 40274120,
                        "nodeId": 19,
                        "registerId": 1,
                        "factorName": "主卧-温度-GZ-10",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_19_2",
                        "deviceAddr": 40274120,
                        "nodeId": 19,
                        "registerId": 2,
                        "factorName": "主卧-湿度-GZ-10",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_20_5",
                        "deviceAddr": 40274120,
                        "nodeId": 20,
                        "registerId": 5,
                        "factorName": "厨房-光照-GZ-1",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_21_5",
                        "deviceAddr": 40274120,
                        "nodeId": 21,
                        "registerId": 5,
                        "factorName": "厨房-光照-GZ-2",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_22_5",
                        "deviceAddr": 40274120,
                        "nodeId": 22,
                        "registerId": 5,
                        "factorName": "厨房-光照-GZ-4",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_23_5",
                        "deviceAddr": 40274120,
                        "nodeId": 23,
                        "registerId": 5,
                        "factorName": "西厨-光照-GZ-3",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_24_5",
                        "deviceAddr": 40274120,
                        "nodeId": 24,
                        "registerId": 5,
                        "factorName": "卧室2-光照-GZ-6",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_25_5",
                        "deviceAddr": 40274120,
                        "nodeId": 25,
                        "registerId": 5,
                        "factorName": "卧室2-光照-GZ-7",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_26_5",
                        "deviceAddr": 40274120,
                        "nodeId": 26,
                        "registerId": 5,
                        "factorName": "餐厅-光照-GZ-5",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_27_5",
                        "deviceAddr": 40274120,
                        "nodeId": 27,
                        "registerId": 5,
                        "factorName": "阳台-光照-GZ-8",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_28_5",
                        "deviceAddr": 40274120,
                        "nodeId": 28,
                        "registerId": 5,
                        "factorName": "阳台-光照-GZ-9",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_29_5",
                        "deviceAddr": 40274120,
                        "nodeId": 29,
                        "registerId": 5,
                        "factorName": "主卧-光照-GZ-10",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_30_5",
                        "deviceAddr": 40274120,
                        "nodeId": 30,
                        "registerId": 5,
                        "factorName": "卧室3-光照-GZ-11",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_31_5",
                        "deviceAddr": 40274120,
                        "nodeId": 31,
                        "registerId": 5,
                        "factorName": "光照",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40274120_32_5",
                        "deviceAddr": 40274120,
                        "nodeId": 32,
                        "registerId": 5,
                        "factorName": "光照",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "Lux",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    }
                ],
                "deviceCode": "7614b5e09bfaa9ad886062d6b4492abd",
                "protocol": "v2"
            }
        },
        environmentSensor: {
            "code": 1000,
            "message": "成功",
            "data": {
                "deviceAddr": 40287568,
                "groupId": "c166f67a8f504f97bafd10e0c9032e21",
                "deviceName": "室外气象环境监测站",
                "offlineinterval": 10,
                "savedatainterval": 5,
                "alarmSwitch": 3,
                "alarmRecord": 1,
                "lng": 115.988705,
                "lat": 40.448054,
                "useMarkLocation": true,
                "sort": 0,
                "deviceType": "",
                "factors": [
                    {
                        "factorId": "40287568_1_1",
                        "deviceAddr": 40287568,
                        "nodeId": 1,
                        "registerId": 1,
                        "factorName": "风力",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 0,
                        "unit": "级",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40287568_1_2",
                        "deviceAddr": 40287568,
                        "nodeId": 1,
                        "registerId": 2,
                        "factorName": "风速",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "m/s",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40287568_2_1",
                        "deviceAddr": 40287568,
                        "nodeId": 2,
                        "registerId": 1,
                        "factorName": "风向",
                        "factorIcon": "0.png",
                        "coefficient": 1.0,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 2,
                        "unit": "方向",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40287568_11_1",
                        "deviceAddr": 40287568,
                        "nodeId": 11,
                        "registerId": 1,
                        "factorName": "空气温度",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "℃",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    },
                    {
                        "factorId": "40287568_11_2",
                        "deviceAddr": 40287568,
                        "nodeId": 11,
                        "registerId": 2,
                        "factorName": "空气湿度",
                        "factorIcon": "0.png",
                        "coefficient": 0.1,
                        "offset": 0.0,
                        "alarmDelay": 0,
                        "backToNormalDelay": 0,
                        "alarmPeriodBegin": "00:00",
                        "alarmPeriodEnd": "23:59",
                        "alarmRate": 5,
                        "digits": 1,
                        "unit": "%",
                        "enabled": true,
                        "sort": 0,
                        "maxVoiceAlarmTimes": 3,
                        "maxSmsAlarmTimes": 3,
                        "maxEmailAlarmTimes": 3,
                        "maxWeChatAlarmTimes": 3
                    }
                ],
                "deviceCode": "4e736bd353f2b2b0cf5b9f0e961cda20",
                "protocol": "v2"
            }
        },
        
    },
    reducers: {
        changeIndexAction(state, { payload }) {
            state.index = payload
        },
    }
})

export const {
    changeIndexAction
} = historicDataSlice.actions

export default historicDataSlice.reducer
